name: Tests
on: 
    push:
jobs:
    build-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - name: Install googletest
              uses: Bacondish2023/setup-googletest@v1
              with:
                tag: v1.14.0

            - name: Run Tests
              run: |
               cd ${{github.workspace}}/test
               cmake -S . -B build
               cmake --build build
               cd build && ctest
